version: '3.9'
services:
  react:
    build: .
    ports: 
      - "80:80"
    volumes:
      - .:/app
  api:
    build: ./server
    ports:
      - "4000:4000"
    command:
      sh -c "nodemon --legacy-watch index"