# Workflows นี้จะทำการติดตั้งขึ้นต่อกันของโหนดใหม่ทั้งหมด สร้างซอร์สโค้ด และ รันการทดสอบในเวอร์ชันต่างๆ ของ node
name: Node.js CI

on:
  push: # การ push workflows ขึ้นไปทำงานที่ branch ไหน?
    branches: [main]
  pull_request: # การ pull workflows กลับมาจาก branch ไหน?
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest #รันโดย base on ubuntu เวอร์ชั่นล่าสุด

    strategy:
      matrix: # ตัวช่วยในการสร้างการรันงานได้หลายรายการ
        node-version: [10.x, 12.x, 14.x] # ซึ่งเลือกมาทั้งหมด 3 versions ของ node

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci # ทำการรัน CI
      - run: npm build # ทำการ build production
      - run: npm test # เช็ค test case ต่างๆ หา error